//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioCorreo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaParametro", Namespace="http://tempuri.org/")]
    public partial class ListaParametro : object
    {
        
        private EnvioCorreo.Parametro[] listaField;
        
        private EnvioCorreo.Parametro[] vectorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EnvioCorreo.Parametro[] lista
        {
            get
            {
                return this.listaField;
            }
            set
            {
                this.listaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EnvioCorreo.Parametro[] vector
        {
            get
            {
                return this.vectorField;
            }
            set
            {
                this.vectorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametro", Namespace="http://tempuri.org/")]
    public partial class Parametro : object
    {
        
        private string nombreField;
        
        private string valorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnvioCorreo.ServicioEnvioCorreoReporteSoap")]
    public interface ServicioEnvioCorreoReporteSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clsEnviarReporteHTML", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteHTMLResponse> clsEnviarReporteHTMLAsync(EnvioCorreo.clsEnviarReporteHTMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarReporteHTML", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteHTMLResponse> sEnviarReporteHTMLAsync(EnvioCorreo.sEnviarReporteHTMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarCorreoResponse> sEnviarCorreoAsync(EnvioCorreo.sEnviarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clsEnviarReportePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReportePDFResponse> clsEnviarReportePDFAsync(EnvioCorreo.clsEnviarReportePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarReportePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReportePDFResponse> sEnviarReportePDFAsync(EnvioCorreo.sEnviarReportePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clsEnviarReporteEXCEL", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteEXCELResponse> clsEnviarReporteEXCELAsync(EnvioCorreo.clsEnviarReporteEXCELRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarReporteEXCEL", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteEXCELResponse> sEnviarReporteEXCELAsync(EnvioCorreo.sEnviarReporteEXCELRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clsEnviarReporteWORD", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteWORDResponse> clsEnviarReporteWORDAsync(EnvioCorreo.clsEnviarReporteWORDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarReporteWORD", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteWORDResponse> sEnviarReporteWORDAsync(EnvioCorreo.sEnviarReporteWORDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarReportePruebas", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReportePruebasResponse> sEnviarReportePruebasAsync(EnvioCorreo.sEnviarReportePruebasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getReporteHTML", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.getReporteHTMLResponse> getReporteHTMLAsync(EnvioCorreo.getReporteHTMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sEnviarAdjuntoTxt", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarAdjuntoTxtResponse> sEnviarAdjuntoTxtAsync(EnvioCorreo.sEnviarAdjuntoTxtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/binEnviarReporteEXCEL", ReplyAction="*")]
        System.Threading.Tasks.Task<EnvioCorreo.binEnviarReporteEXCELResponse> binEnviarReporteEXCELAsync(EnvioCorreo.binEnviarReporteEXCELRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReporteHTMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReporteHTML", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReporteHTMLRequestBody Body;
        
        public clsEnviarReporteHTMLRequest()
        {
        }
        
        public clsEnviarReporteHTMLRequest(EnvioCorreo.clsEnviarReporteHTMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEnviarReporteHTMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public EnvioCorreo.ListaParametro parametros;
        
        public clsEnviarReporteHTMLRequestBody()
        {
        }
        
        public clsEnviarReporteHTMLRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, EnvioCorreo.ListaParametro parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReporteHTMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReporteHTMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReporteHTMLResponseBody Body;
        
        public clsEnviarReporteHTMLResponse()
        {
        }
        
        public clsEnviarReporteHTMLResponse(EnvioCorreo.clsEnviarReporteHTMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class clsEnviarReporteHTMLResponseBody
    {
        
        public clsEnviarReporteHTMLResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReporteHTMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReporteHTML", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReporteHTMLRequestBody Body;
        
        public sEnviarReporteHTMLRequest()
        {
        }
        
        public sEnviarReporteHTMLRequest(EnvioCorreo.sEnviarReporteHTMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarReporteHTMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string parametros;
        
        public sEnviarReporteHTMLRequestBody()
        {
        }
        
        public sEnviarReporteHTMLRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReporteHTMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReporteHTMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReporteHTMLResponseBody Body;
        
        public sEnviarReporteHTMLResponse()
        {
        }
        
        public sEnviarReporteHTMLResponse(EnvioCorreo.sEnviarReporteHTMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarReporteHTMLResponseBody
    {
        
        public sEnviarReporteHTMLResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarCorreoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarCorreo", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarCorreoRequestBody Body;
        
        public sEnviarCorreoRequest()
        {
        }
        
        public sEnviarCorreoRequest(EnvioCorreo.sEnviarCorreoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarCorreoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        public sEnviarCorreoRequestBody()
        {
        }
        
        public sEnviarCorreoRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarCorreoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarCorreoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarCorreoResponseBody Body;
        
        public sEnviarCorreoResponse()
        {
        }
        
        public sEnviarCorreoResponse(EnvioCorreo.sEnviarCorreoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarCorreoResponseBody
    {
        
        public sEnviarCorreoResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReportePDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReportePDF", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReportePDFRequestBody Body;
        
        public clsEnviarReportePDFRequest()
        {
        }
        
        public clsEnviarReportePDFRequest(EnvioCorreo.clsEnviarReportePDFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEnviarReportePDFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public EnvioCorreo.ListaParametro parametros;
        
        public clsEnviarReportePDFRequestBody()
        {
        }
        
        public clsEnviarReportePDFRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, EnvioCorreo.ListaParametro parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReportePDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReportePDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReportePDFResponseBody Body;
        
        public clsEnviarReportePDFResponse()
        {
        }
        
        public clsEnviarReportePDFResponse(EnvioCorreo.clsEnviarReportePDFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class clsEnviarReportePDFResponseBody
    {
        
        public clsEnviarReportePDFResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReportePDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReportePDF", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReportePDFRequestBody Body;
        
        public sEnviarReportePDFRequest()
        {
        }
        
        public sEnviarReportePDFRequest(EnvioCorreo.sEnviarReportePDFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarReportePDFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string parametros;
        
        public sEnviarReportePDFRequestBody()
        {
        }
        
        public sEnviarReportePDFRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReportePDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReportePDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReportePDFResponseBody Body;
        
        public sEnviarReportePDFResponse()
        {
        }
        
        public sEnviarReportePDFResponse(EnvioCorreo.sEnviarReportePDFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarReportePDFResponseBody
    {
        
        public sEnviarReportePDFResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReporteEXCELRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReporteEXCEL", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReporteEXCELRequestBody Body;
        
        public clsEnviarReporteEXCELRequest()
        {
        }
        
        public clsEnviarReporteEXCELRequest(EnvioCorreo.clsEnviarReporteEXCELRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEnviarReporteEXCELRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public EnvioCorreo.ListaParametro parametros;
        
        public clsEnviarReporteEXCELRequestBody()
        {
        }
        
        public clsEnviarReporteEXCELRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, EnvioCorreo.ListaParametro parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReporteEXCELResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReporteEXCELResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReporteEXCELResponseBody Body;
        
        public clsEnviarReporteEXCELResponse()
        {
        }
        
        public clsEnviarReporteEXCELResponse(EnvioCorreo.clsEnviarReporteEXCELResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class clsEnviarReporteEXCELResponseBody
    {
        
        public clsEnviarReporteEXCELResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReporteEXCELRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReporteEXCEL", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReporteEXCELRequestBody Body;
        
        public sEnviarReporteEXCELRequest()
        {
        }
        
        public sEnviarReporteEXCELRequest(EnvioCorreo.sEnviarReporteEXCELRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarReporteEXCELRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string parametros;
        
        public sEnviarReporteEXCELRequestBody()
        {
        }
        
        public sEnviarReporteEXCELRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReporteEXCELResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReporteEXCELResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReporteEXCELResponseBody Body;
        
        public sEnviarReporteEXCELResponse()
        {
        }
        
        public sEnviarReporteEXCELResponse(EnvioCorreo.sEnviarReporteEXCELResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarReporteEXCELResponseBody
    {
        
        public sEnviarReporteEXCELResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReporteWORDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReporteWORD", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReporteWORDRequestBody Body;
        
        public clsEnviarReporteWORDRequest()
        {
        }
        
        public clsEnviarReporteWORDRequest(EnvioCorreo.clsEnviarReporteWORDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class clsEnviarReporteWORDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public EnvioCorreo.ListaParametro parametros;
        
        public clsEnviarReporteWORDRequestBody()
        {
        }
        
        public clsEnviarReporteWORDRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, EnvioCorreo.ListaParametro parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clsEnviarReporteWORDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clsEnviarReporteWORDResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.clsEnviarReporteWORDResponseBody Body;
        
        public clsEnviarReporteWORDResponse()
        {
        }
        
        public clsEnviarReporteWORDResponse(EnvioCorreo.clsEnviarReporteWORDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class clsEnviarReporteWORDResponseBody
    {
        
        public clsEnviarReporteWORDResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReporteWORDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReporteWORD", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReporteWORDRequestBody Body;
        
        public sEnviarReporteWORDRequest()
        {
        }
        
        public sEnviarReporteWORDRequest(EnvioCorreo.sEnviarReporteWORDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarReporteWORDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string parametros;
        
        public sEnviarReporteWORDRequestBody()
        {
        }
        
        public sEnviarReporteWORDRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReporteWORDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReporteWORDResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReporteWORDResponseBody Body;
        
        public sEnviarReporteWORDResponse()
        {
        }
        
        public sEnviarReporteWORDResponse(EnvioCorreo.sEnviarReporteWORDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarReporteWORDResponseBody
    {
        
        public sEnviarReporteWORDResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReportePruebasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReportePruebas", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReportePruebasRequestBody Body;
        
        public sEnviarReportePruebasRequest()
        {
        }
        
        public sEnviarReportePruebasRequest(EnvioCorreo.sEnviarReportePruebasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarReportePruebasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string parametros;
        
        public sEnviarReportePruebasRequestBody()
        {
        }
        
        public sEnviarReportePruebasRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.archivoReporte = archivoReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarReportePruebasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarReportePruebasResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarReportePruebasResponseBody Body;
        
        public sEnviarReportePruebasResponse()
        {
        }
        
        public sEnviarReportePruebasResponse(EnvioCorreo.sEnviarReportePruebasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarReportePruebasResponseBody
    {
        
        public sEnviarReportePruebasResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReporteHTMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReporteHTML", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.getReporteHTMLRequestBody Body;
        
        public getReporteHTMLRequest()
        {
        }
        
        public getReporteHTMLRequest(EnvioCorreo.getReporteHTMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReporteHTMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string servidor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombreReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parametros;
        
        public getReporteHTMLRequestBody()
        {
        }
        
        public getReporteHTMLRequestBody(string servidor, string carpeta, string nombreReporte, string parametros)
        {
            this.servidor = servidor;
            this.carpeta = carpeta;
            this.nombreReporte = nombreReporte;
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReporteHTMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReporteHTMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.getReporteHTMLResponseBody Body;
        
        public getReporteHTMLResponse()
        {
        }
        
        public getReporteHTMLResponse(EnvioCorreo.getReporteHTMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReporteHTMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReporteHTMLResult;
        
        public getReporteHTMLResponseBody()
        {
        }
        
        public getReporteHTMLResponseBody(string getReporteHTMLResult)
        {
            this.getReporteHTMLResult = getReporteHTMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarAdjuntoTxtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarAdjuntoTxt", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarAdjuntoTxtRequestBody Body;
        
        public sEnviarAdjuntoTxtRequest()
        {
        }
        
        public sEnviarAdjuntoTxtRequest(EnvioCorreo.sEnviarAdjuntoTxtRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sEnviarAdjuntoTxtRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string conexion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string parametros;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string delimitador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string nombres_archivo;
        
        public sEnviarAdjuntoTxtRequestBody()
        {
        }
        
        public sEnviarAdjuntoTxtRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string conexion, string parametros, string delimitador, string nombres_archivo)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.conexion = conexion;
            this.parametros = parametros;
            this.delimitador = delimitador;
            this.nombres_archivo = nombres_archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sEnviarAdjuntoTxtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sEnviarAdjuntoTxtResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.sEnviarAdjuntoTxtResponseBody Body;
        
        public sEnviarAdjuntoTxtResponse()
        {
        }
        
        public sEnviarAdjuntoTxtResponse(EnvioCorreo.sEnviarAdjuntoTxtResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sEnviarAdjuntoTxtResponseBody
    {
        
        public sEnviarAdjuntoTxtResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binEnviarReporteEXCELRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binEnviarReporteEXCEL", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.binEnviarReporteEXCELRequestBody Body;
        
        public binEnviarReporteEXCELRequest()
        {
        }
        
        public binEnviarReporteEXCELRequest(EnvioCorreo.binEnviarReporteEXCELRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class binEnviarReporteEXCELRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aliasRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string copia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string copiaOculta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cuerpoMensaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string archivoReporte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] archivo;
        
        public binEnviarReporteEXCELRequestBody()
        {
        }
        
        public binEnviarReporteEXCELRequestBody(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string archivoReporte, byte[] archivo)
        {
            this.asunto = asunto;
            this.remitente = remitente;
            this.aliasRemitente = aliasRemitente;
            this.destinatario = destinatario;
            this.copia = copia;
            this.copiaOculta = copiaOculta;
            this.cuerpoMensaje = cuerpoMensaje;
            this.archivoReporte = archivoReporte;
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class binEnviarReporteEXCELResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="binEnviarReporteEXCELResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnvioCorreo.binEnviarReporteEXCELResponseBody Body;
        
        public binEnviarReporteEXCELResponse()
        {
        }
        
        public binEnviarReporteEXCELResponse(EnvioCorreo.binEnviarReporteEXCELResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class binEnviarReporteEXCELResponseBody
    {
        
        public binEnviarReporteEXCELResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServicioEnvioCorreoReporteSoapChannel : EnvioCorreo.ServicioEnvioCorreoReporteSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServicioEnvioCorreoReporteSoapClient : System.ServiceModel.ClientBase<EnvioCorreo.ServicioEnvioCorreoReporteSoap>, EnvioCorreo.ServicioEnvioCorreoReporteSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEnvioCorreoReporteSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEnvioCorreoReporteSoapClient.GetBindingForEndpoint(endpointConfiguration), ServicioEnvioCorreoReporteSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEnvioCorreoReporteSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEnvioCorreoReporteSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEnvioCorreoReporteSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEnvioCorreoReporteSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEnvioCorreoReporteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteHTMLResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.clsEnviarReporteHTMLAsync(EnvioCorreo.clsEnviarReporteHTMLRequest request)
        {
            return base.Channel.clsEnviarReporteHTMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteHTMLResponse> clsEnviarReporteHTMLAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, EnvioCorreo.ListaParametro parametros)
        {
            EnvioCorreo.clsEnviarReporteHTMLRequest inValue = new EnvioCorreo.clsEnviarReporteHTMLRequest();
            inValue.Body = new EnvioCorreo.clsEnviarReporteHTMLRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).clsEnviarReporteHTMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteHTMLResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarReporteHTMLAsync(EnvioCorreo.sEnviarReporteHTMLRequest request)
        {
            return base.Channel.sEnviarReporteHTMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteHTMLResponse> sEnviarReporteHTMLAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string parametros)
        {
            EnvioCorreo.sEnviarReporteHTMLRequest inValue = new EnvioCorreo.sEnviarReporteHTMLRequest();
            inValue.Body = new EnvioCorreo.sEnviarReporteHTMLRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarReporteHTMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarCorreoResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarCorreoAsync(EnvioCorreo.sEnviarCorreoRequest request)
        {
            return base.Channel.sEnviarCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarCorreoResponse> sEnviarCorreoAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje)
        {
            EnvioCorreo.sEnviarCorreoRequest inValue = new EnvioCorreo.sEnviarCorreoRequest();
            inValue.Body = new EnvioCorreo.sEnviarCorreoRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReportePDFResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.clsEnviarReportePDFAsync(EnvioCorreo.clsEnviarReportePDFRequest request)
        {
            return base.Channel.clsEnviarReportePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReportePDFResponse> clsEnviarReportePDFAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, EnvioCorreo.ListaParametro parametros)
        {
            EnvioCorreo.clsEnviarReportePDFRequest inValue = new EnvioCorreo.clsEnviarReportePDFRequest();
            inValue.Body = new EnvioCorreo.clsEnviarReportePDFRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).clsEnviarReportePDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReportePDFResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarReportePDFAsync(EnvioCorreo.sEnviarReportePDFRequest request)
        {
            return base.Channel.sEnviarReportePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarReportePDFResponse> sEnviarReportePDFAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            EnvioCorreo.sEnviarReportePDFRequest inValue = new EnvioCorreo.sEnviarReportePDFRequest();
            inValue.Body = new EnvioCorreo.sEnviarReportePDFRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarReportePDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteEXCELResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.clsEnviarReporteEXCELAsync(EnvioCorreo.clsEnviarReporteEXCELRequest request)
        {
            return base.Channel.clsEnviarReporteEXCELAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteEXCELResponse> clsEnviarReporteEXCELAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, EnvioCorreo.ListaParametro parametros)
        {
            EnvioCorreo.clsEnviarReporteEXCELRequest inValue = new EnvioCorreo.clsEnviarReporteEXCELRequest();
            inValue.Body = new EnvioCorreo.clsEnviarReporteEXCELRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).clsEnviarReporteEXCELAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteEXCELResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarReporteEXCELAsync(EnvioCorreo.sEnviarReporteEXCELRequest request)
        {
            return base.Channel.sEnviarReporteEXCELAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteEXCELResponse> sEnviarReporteEXCELAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            EnvioCorreo.sEnviarReporteEXCELRequest inValue = new EnvioCorreo.sEnviarReporteEXCELRequest();
            inValue.Body = new EnvioCorreo.sEnviarReporteEXCELRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarReporteEXCELAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteWORDResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.clsEnviarReporteWORDAsync(EnvioCorreo.clsEnviarReporteWORDRequest request)
        {
            return base.Channel.clsEnviarReporteWORDAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.clsEnviarReporteWORDResponse> clsEnviarReporteWORDAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, EnvioCorreo.ListaParametro parametros)
        {
            EnvioCorreo.clsEnviarReporteWORDRequest inValue = new EnvioCorreo.clsEnviarReporteWORDRequest();
            inValue.Body = new EnvioCorreo.clsEnviarReporteWORDRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).clsEnviarReporteWORDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteWORDResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarReporteWORDAsync(EnvioCorreo.sEnviarReporteWORDRequest request)
        {
            return base.Channel.sEnviarReporteWORDAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarReporteWORDResponse> sEnviarReporteWORDAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            EnvioCorreo.sEnviarReporteWORDRequest inValue = new EnvioCorreo.sEnviarReporteWORDRequest();
            inValue.Body = new EnvioCorreo.sEnviarReporteWORDRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarReporteWORDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarReportePruebasResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarReportePruebasAsync(EnvioCorreo.sEnviarReportePruebasRequest request)
        {
            return base.Channel.sEnviarReportePruebasAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarReportePruebasResponse> sEnviarReportePruebasAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string servidor, string carpeta, string nombreReporte, string archivoReporte, string parametros)
        {
            EnvioCorreo.sEnviarReportePruebasRequest inValue = new EnvioCorreo.sEnviarReportePruebasRequest();
            inValue.Body = new EnvioCorreo.sEnviarReportePruebasRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarReportePruebasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.getReporteHTMLResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.getReporteHTMLAsync(EnvioCorreo.getReporteHTMLRequest request)
        {
            return base.Channel.getReporteHTMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.getReporteHTMLResponse> getReporteHTMLAsync(string servidor, string carpeta, string nombreReporte, string parametros)
        {
            EnvioCorreo.getReporteHTMLRequest inValue = new EnvioCorreo.getReporteHTMLRequest();
            inValue.Body = new EnvioCorreo.getReporteHTMLRequestBody();
            inValue.Body.servidor = servidor;
            inValue.Body.carpeta = carpeta;
            inValue.Body.nombreReporte = nombreReporte;
            inValue.Body.parametros = parametros;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).getReporteHTMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.sEnviarAdjuntoTxtResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.sEnviarAdjuntoTxtAsync(EnvioCorreo.sEnviarAdjuntoTxtRequest request)
        {
            return base.Channel.sEnviarAdjuntoTxtAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.sEnviarAdjuntoTxtResponse> sEnviarAdjuntoTxtAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string conexion, string parametros, string delimitador, string nombres_archivo)
        {
            EnvioCorreo.sEnviarAdjuntoTxtRequest inValue = new EnvioCorreo.sEnviarAdjuntoTxtRequest();
            inValue.Body = new EnvioCorreo.sEnviarAdjuntoTxtRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.conexion = conexion;
            inValue.Body.parametros = parametros;
            inValue.Body.delimitador = delimitador;
            inValue.Body.nombres_archivo = nombres_archivo;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).sEnviarAdjuntoTxtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnvioCorreo.binEnviarReporteEXCELResponse> EnvioCorreo.ServicioEnvioCorreoReporteSoap.binEnviarReporteEXCELAsync(EnvioCorreo.binEnviarReporteEXCELRequest request)
        {
            return base.Channel.binEnviarReporteEXCELAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnvioCorreo.binEnviarReporteEXCELResponse> binEnviarReporteEXCELAsync(string asunto, string remitente, string aliasRemitente, string destinatario, string copia, string copiaOculta, string cuerpoMensaje, string archivoReporte, byte[] archivo)
        {
            EnvioCorreo.binEnviarReporteEXCELRequest inValue = new EnvioCorreo.binEnviarReporteEXCELRequest();
            inValue.Body = new EnvioCorreo.binEnviarReporteEXCELRequestBody();
            inValue.Body.asunto = asunto;
            inValue.Body.remitente = remitente;
            inValue.Body.aliasRemitente = aliasRemitente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.copia = copia;
            inValue.Body.copiaOculta = copiaOculta;
            inValue.Body.cuerpoMensaje = cuerpoMensaje;
            inValue.Body.archivoReporte = archivoReporte;
            inValue.Body.archivo = archivo;
            return ((EnvioCorreo.ServicioEnvioCorreoReporteSoap)(this)).binEnviarReporteEXCELAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioEnvioCorreoReporteSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServicioEnvioCorreoReporteSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioEnvioCorreoReporteSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://vmappweb-srv.campero.com/wsEnvioCorreo/ServicioEnvioCorreoReporte.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServicioEnvioCorreoReporteSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://vmappweb-srv.campero.com/wsEnvioCorreo/ServicioEnvioCorreoReporte.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioEnvioCorreoReporteSoap,
            
            ServicioEnvioCorreoReporteSoap12,
        }
    }
}
